---
server:
  port: '${REWARDS_SERVER_PORT:8082}'
  tomcat:
    threads:
      minSpare: '${REWARDS_SERVER_THREADS_MIN:10}'
      max: '${REWARDS_SERVER_THREADS_MAX:1024}'

spring:
  mvc:
    servlet:
      load-on-startup: 1

management:
  server:
    address: "${REWARDS_MANAGEMENT_ADDR:127.0.0.1}"
    port: "${REWARDS_MANAGEMENT_PORT:-1}"
