version: '3.4'
services:
  gps-gateway:
    image: dockercloud/haproxy
    links:
      - gps-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BALANCE=leastconn
  gps-service:
    build:
      context: .
      target: gps
    environment:
      - GPS_SERVER_PORT=8081
      - GPS_SERVER_THREADS_MIN=128
      - GPS_SERVER_THREADS_MAX=128
    deploy:
      replicas: 10
  rewards-gateway:
    image: dockercloud/haproxy
    links:
      - rewards-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MAXCONN=6144
      - BALANCE=leastconn
  rewards-service:
    build:
      context: .
      target: rewards
    environment:
      - REWARDS_SERVER_PORT=8082
      - REWARDS_SERVER_THREADS_MIN=128
      - REWARDS_SERVER_THREADS_MAX=2048
    deploy:
      replicas: 3
  users-service:
    build:
      context: .
      target: users
    environment:
      - USERS_SERVER_PORT=8080
      - INTERNAL_USERS_NUMBER=100000
      - GPS_SERVICE_URL=http://gps-gateway/
      - GPS_SERVICE_MAX_REQUESTS=1024
      - REWARDS_SERVICE_URL=http://rewards-gateway/
      - REWARDS_SERVICE_MAX_REQUESTS=6144
    links:
      - gps-gateway
      - rewards-service
    ports:
      - 80:8080
