---
server:
  port: '${USERS_SERVER_PORT:8080}'

management:
  server:
    address: "${USERS_MANAGEMENT_ADDR:127.0.0.1}"
    port: "${USERS_MANAGEMENT_PORT:-1}"

tourguide:
  internal-users:
    number: '${INTERNAL_USERS_NUMBER:100}'
  tracking:
    proximity-buffer: '${TRACKING_PROXIMITY_BUFFER:10}'
  gps-service:
    url: '${GPS_SERVICE_URL:http://127.0.0.1:8081/}'
    max-concurrent-requests: '${GPS_SERVICE_MAX_REQUESTS:128}'
  rewards-service:
    url: '${REWARDS_SERVICE_URL:http://127.0.0.1:8082/}'
    max-concurrent-requests: '${REWARDS_SERVICE_MAX_REQUESTS:1024}'

logging.level.com.tourguide: DEBUG
